package com.projeto.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Aprovacao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String mensagem;

	private boolean aprovado = true;

	public Aprovacao() {
	}

	public java.lang.String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(java.lang.String mensagem) {
		this.mensagem = mensagem;
	}

	public boolean isAprovado() {
		return this.aprovado;
	}

	public void setAprovado(boolean aprovado) {
		this.aprovado = aprovado;
	}

	public Aprovacao(java.lang.String mensagem, boolean aprovado) {
		this.mensagem = mensagem;
		this.aprovado = aprovado;
	}

}