package com.projeto.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Compra implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String produto;
	private java.lang.String principioAtivo;
	private int quantidade;
	private int quantidadeTotal;
    private int total = 0;

	public Compra() {
	}

	public java.lang.String getProduto() {
		return this.produto;
	}

	public void setProduto(java.lang.String produto) {
		this.produto = produto;
	}

	public java.lang.String getPrincipioAtivo() {
		return this.principioAtivo;
	}

	public void setPrincipioAtivo(java.lang.String principioAtivo) {
		this.principioAtivo = principioAtivo;
	}

	public int getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}

	public int getQuantidadeTotal() {
	    total += this.quantidade;
		return total;
	}

	public void setQuantidadeTotal(int quantidadeTotal) {
		this.quantidadeTotal = total;
	}

	public Compra(java.lang.String produto, java.lang.String principioAtivo,
			int quantidade, int quantidadeTotal) {
		this.produto = produto;
		this.principioAtivo = principioAtivo;
		this.quantidade = quantidade;
		this.quantidadeTotal = total;
	}

}